import type {
  HardwareProgressNote,
  HardwareUnit,
  TestLogEntry,
  VehicleProcess,
} from './types'

/** Seed inventory — shared defaults for the team lab API and local fallback. */
export const SEED_HARDWARE: HardwareUnit[] = [
  {
    id: 'hw-stravox-b1m',
    name: 'STRAVOX airframe',
    kind: 'vehicle',
    serial: 'SVX-B1M-001',
    hwRev: 'B1M · rev A',
    fwVersion: '',
    status: 'assembly',
    location: 'Goods Shed',
    owner: 'Structures',
    notes: 'Primary flight vehicle for B1M campaign.',
    updatedAt: '2026-07-20T10:00:00.000Z',
  },
  {
    id: 'hw-motor-b1m',
    name: 'B1M motor',
    kind: 'motor',
    serial: 'MTR-B1M-001',
    hwRev: 'B1M · grain set 1',
    status: 'checkout',
    location: 'Goods Shed · prop bay',
    owner: 'Propulsion',
    notes: 'Static-fire candidate. Case temp instrumentation fitted.',
    updatedAt: '2026-07-22T08:30:00.000Z',
  },
  {
    id: 'hw-avionics-01',
    name: 'Flight computer',
    kind: 'avionics',
    serial: 'AVN-FC-01',
    hwRev: 'rev B',
    fwVersion: '0.4.2-dev',
    status: 'checkout',
    location: 'Goods Shed · bench',
    owner: 'Avionics',
    notes: 'Downlink dry-run load. GPS path not fully exercised.',
    updatedAt: '2026-07-24T14:15:00.000Z',
  },
  {
    id: 'hw-pad-stand',
    name: 'Static-fire stand',
    kind: 'pad',
    serial: 'PAD-SF-01',
    hwRev: 'rev C',
    status: 'flight-ready',
    location: 'Pad',
    owner: 'Structures',
    notes: 'Load path verified. Thrust cell cal current.',
    updatedAt: '2026-07-18T16:00:00.000Z',
  },
  {
    id: 'hw-logger',
    name: 'Goods Shed logger',
    kind: 'ground',
    serial: 'GSE-LOG-01',
    hwRev: 'rev A',
    fwVersion: '1.1.0',
    status: 'flight-ready',
    location: 'Goods Shed',
    owner: 'Ops',
    notes: 'Records pad instruments during burns.',
    updatedAt: '2026-07-15T09:00:00.000Z',
  },
  {
    id: 'inv-an-bolts',
    name: 'AN-4 bolts',
    kind: 'part',
    serial: 'INV-AN4-BOLT',
    partNumber: 'AN4-14A',
    quantity: 48,
    hwRev: '—',
    status: 'flight-ready',
    location: 'Goods Shed · fastener bin',
    owner: 'Structures',
    notes: 'Airframe hardware stock.',
    updatedAt: '2026-07-28T10:00:00.000Z',
  },
  {
    id: 'inv-epoxy',
    name: 'Structural epoxy',
    kind: 'consumable',
    serial: 'INV-EPOXY-01',
    partNumber: 'Hysol EA 9394',
    quantity: 4,
    hwRev: '—',
    status: 'flight-ready',
    location: 'Goods Shed · chem cabinet',
    owner: 'Structures',
    notes: 'Keep cold. Check expiry before bond ops.',
    updatedAt: '2026-07-28T10:00:00.000Z',
  },
  {
    id: 'inv-torque-wrench',
    name: 'Torque wrench 5–25 Nm',
    kind: 'tool',
    serial: 'TOOL-TQ-05',
    quantity: 1,
    hwRev: '—',
    status: 'flight-ready',
    location: 'Goods Shed · tool wall',
    owner: 'Ops',
    notes: 'Cal due before B1M static fire.',
    updatedAt: '2026-07-28T10:00:00.000Z',
  },
]

export const SEED_PROGRESS: HardwareProgressNote[] = [
  {
    id: 'pg-1',
    unitId: 'hw-motor-b1m',
    date: '2026-07-22',
    status: 'checkout',
    note: 'Grain set installed. Chamber pressure tap leak-checked.',
    author: 'Propulsion',
  },
  {
    id: 'pg-2',
    unitId: 'hw-stravox-b1m',
    date: '2026-07-20',
    status: 'assembly',
    note: 'Fin can and motor interface dry-fit complete.',
    author: 'Structures',
  },
  {
    id: 'pg-3',
    unitId: 'hw-avionics-01',
    date: '2026-07-24',
    status: 'checkout',
    note: 'FW 0.4.2-dev flashed. Packet path to shed logger OK in bench loop.',
    author: 'Avionics',
  },
  {
    id: 'pg-4',
    unitId: 'hw-pad-stand',
    date: '2026-07-18',
    status: 'flight-ready',
    note: 'Thrust cell zeroed and span-checked against known mass.',
    author: 'Ops',
  },
]

export const SEED_TESTS: TestLogEntry[] = [
  {
    id: 'test-1',
    date: '2026-07-12',
    title: 'Pad stand load check',
    kind: 'structural',
    result: 'pass',
    unitIds: ['hw-pad-stand', 'hw-logger'],
    site: 'Pad',
    operator: 'Ops',
    summary: 'Static load path and logger capture verified with deadweight.',
    metrics: [
      { key: 'peak_load', value: '120', unit: 'kgf' },
      { key: 'sample_rate', value: '200', unit: 'Hz' },
    ],
    dataRef: 'Drive · test campaign / 2026-07-12-pad-load',
    createdAt: '2026-07-12T17:00:00.000Z',
  },
  {
    id: 'test-2',
    date: '2026-07-24',
    title: 'Avionics downlink dry run',
    kind: 'avionics',
    result: 'partial',
    unitIds: ['hw-avionics-01', 'hw-logger'],
    site: 'Goods Shed',
    operator: 'Avionics',
    summary:
      'Bench RF path into shed logger stable. GPS sats not locked indoors — outdoor retest needed.',
    metrics: [
      { key: 'packet_drop', value: '0.2', unit: '%' },
      { key: 'latency_p95', value: '48', unit: 'ms' },
    ],
    dataRef: 'Drive · test campaign / 2026-07-24-avionics-dry',
    createdAt: '2026-07-24T15:30:00.000Z',
  },
  {
    id: 'test-3',
    date: '2026-07-25',
    title: 'Motor / airframe fit check',
    kind: 'fit-check',
    result: 'pass',
    unitIds: ['hw-motor-b1m', 'hw-stravox-b1m'],
    site: 'Goods Shed',
    operator: 'Structures',
    summary: 'Motor seats cleanly. Retention hardware torque marked.',
    createdAt: '2026-07-25T11:00:00.000Z',
  },
]

/** Seed vehicle / campaign process trackers. */
export const SEED_PROCESSES: VehicleProcess[] = [
  {
    id: 'proc-stravox-b1m',
    vehicleUnitId: 'hw-stravox-b1m',
    name: 'STRAVOX B1M build & checkout',
    campaign: 'B1M',
    notes: 'Path from Goods Shed assembly through static-fire readiness.',
    updatedAt: '2026-07-25T12:00:00.000Z',
    steps: [
      {
        id: 'ps-1',
        order: 1,
        title: 'Airframe dry-fit',
        detail: 'Fin can, motor interface, and recovery bay fit check.',
        owner: 'Structures',
        status: 'done',
        linkedUnitIds: ['hw-stravox-b1m'],
        completedAt: '2026-07-20T16:00:00.000Z',
        completedBy: 'Structures',
      },
      {
        id: 'ps-2',
        order: 2,
        title: 'Motor install & retention',
        detail: 'Seat motor, torque retention, mark hardware.',
        owner: 'Propulsion',
        status: 'done',
        linkedUnitIds: ['hw-motor-b1m', 'hw-stravox-b1m'],
        completedAt: '2026-07-25T11:00:00.000Z',
        completedBy: 'Structures',
      },
      {
        id: 'ps-3',
        order: 3,
        title: 'Avionics integrate & flash',
        detail: 'Install FC, flash current FW, bench downlink loop.',
        owner: 'Avionics',
        status: 'active',
        linkedUnitIds: ['hw-avionics-01', 'hw-stravox-b1m'],
      },
      {
        id: 'ps-4',
        order: 4,
        title: 'GSE / logger checkout',
        detail: 'Confirm shed logger captures pad + vehicle paths.',
        owner: 'Ops',
        status: 'pending',
        linkedUnitIds: ['hw-logger'],
      },
      {
        id: 'ps-5',
        order: 5,
        title: 'Pad stand load path',
        detail: 'Verify stand, thrust cell cal, and instrument harness.',
        owner: 'Structures',
        status: 'pending',
        linkedUnitIds: ['hw-pad-stand'],
      },
      {
        id: 'ps-6',
        order: 6,
        title: 'Static-fire readiness review',
        detail: 'Go / hold review before pad ops.',
        owner: 'Ops',
        status: 'pending',
        linkedUnitIds: ['hw-stravox-b1m', 'hw-motor-b1m'],
      },
      {
        id: 'ps-7',
        order: 7,
        title: 'Flight readiness review',
        detail: 'Final vehicle process gate after static-fire data review.',
        owner: 'Ops',
        status: 'pending',
        linkedUnitIds: ['hw-stravox-b1m'],
      },
    ],
  },
]

